server:
  port: 19870
  mode: debug # debug, release, test

logger:
  level: debug
  path: "./logs"
  development: true
  rotation:
    enabled: true
    max_size: 100
    max_backups: 5
    max_age: 30
    compress: true
  other:
    path: "./logs/other"
    level: info
  categories:
    - name: http
      level: info
    - name: error
      level: error
    - name: business
      level: info
    - name: iam
      level: info
    - name: trafficresource
      level: info

database:
  host: "47.97.154.156"
  port: 11070
  user: "test"
  password: "test@2026"
  dbname: "test"
  searchpath: "test01"

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: your-secret-key-here
  expire: 7200 # seconds

idgen:
  worker_id: 1
