server:
  port: 19870
  mode: debug # debug, release, test

ipfs:
  port: 4800
#  port: 4080
  status: false # 是否开启ipfs服务, 运行环境中没有ipfs会导致初始化失败

logger:
  level: info
  path: "./logs"
  development: true
  rotation:
    enabled: true
    max_size: 15
    max_backups: 5
    max_age: 30
    compress: false
  other:
    path: "./logs/other"
    level: info
  categories:
    - name: http
      level: info
    - name: error
      level: error
    - name: iam
      level: info
    - name: ipfs
      level: info
    - name: scheduler
      level: info

# 主业务数据库
database:
  host: "121.41.129.227"
  port: 16010
  user: "carbonadmin"
  password: "carbonadmin@2026"
  dbname: "carbon"
  searchpath: "yanping"

# 远程源数据数据库
remote_database:
  host: "121.41.129.227"
  port: 16010
  user: "nptadmin"
  password: "nptadmin@2025"
  dbname: "nanping"
  searchpath: "biz"

redis:
  addr: 121.41.129.227:16020
  password: "nanpingredis@2025"
  db: 6
  timeout: 30

jwt:
  secret: carbon-yp
  expire: 7200 # seconds